name: Commit Stage

on:
  workflow_call: 
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/commit-stage--build-artifact.yml
    with:
      artifact: ${{ github.event.repository.name }}
      version: ${{ github.sha }}

  eslint:
    name: ESLint
    uses: ./.github/workflows/commit-stage--run-eslint-on-code.yml

  upload:
    needs: [build]
    name: Upload
    uses: ./.github/workflows/commit-stage--upload-image-to-scaleway-registry.yml
    with:
      image: ${{ needs.build.outputs.artifact }}
      artifact: ${{ needs.build.outputs.artifact }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}
